---

name: 'dotnetcore'

on:
    push: 
        branches: 
            - develop

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up .NET Core 9.0
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.0.100'
            - name: restore
              run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj
            - name: build
              run: dotnet build  src/Presentation/Nop.Web/Nop.Web.csproj --configuration Debug
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: csharp
        
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3